name: Build and create artifact

on:
  pull_request:
    branches: main
  push:
    branches: main
  workflow_dispatch:

env:
  VCPKG_COMMIT_ID: db0473513e5dc73ec6b6f431ff05d2f398eea042

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11.1
        with:
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
          vcpkgJsonGlob: vcpkg.json

      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          configurePreset: build-release-msvc-ninja
          buildPreset: release-msvc-ninja

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: dist/*.7z
